### ISSUE TITLE
gradient computation with inplace operations

### ISSUE THREAD

**Issue by Tzeviya** [vadimkantorov/ctc#2]
Hi,

When running your code I received the following error:

> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

Could it be that there is some problem with the slicing in the `ctc_loss` function?

Thanks :)

**Comment by vadimkantorov** [comment]
Could be! Thanks for your report, I'll check. In the meanwhile, you could run the code under `with torch.autograd.detect_anomaly():`, maybe that'd indicate the problem.

**Comment by Tzeviya** [comment]
Thanks for the quick reply! So far, all I get is:

> Traceback (most recent call last):
>   File "example.py", line 44, in <module>
>     custom_ctc_grad, = torch.autograd.grad(custom_ctc.sum(), logits, retain_graph = True)
>   File "/home/usr/me/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 204, in grad
>     inputs, allow_unused)
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 122]], which is output 0 of SliceBackward, is at version 130; expected version 129 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Which I assume implies a problem with the slicing...

For now I just randomly added `.clone()` to various places, e.g. : `log_probs[0, :, blank].clone()`, and `log_probs_[t].clone()` etc.  I don't know if it's correct to do this but the output seems fine:

```
Custom loss matches: True
Grad matches: True
CE grad matches: True
```

**Comment by vadimkantorov** [comment]
@Tzeviya have you tried to do double-backward here? or just run the `example.py` as is?

**Comment by vadimkantorov** [comment]
as simply running `example.py` works on recent pytorch

**Comment by GCQiu** [comment]
i met the same problem, 

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [256, 122]], which is output 0 of AsStridedBackward0, is at version 130; expected version 129 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by vadimkantorov** [comment]
Could you please post a complete repro? Are you just trying to run `python example.py` or something else? What's your PyTorch version?

**Comment by YangLeiSX** [comment]
I met the same problem.

I'm trying to merge the ctc_loss in ctc.py into my code base to reimplement CTC loss with label priors. then I get RuntimeError in backward process. 

follow the traceback I locate the error in the ctc_loss function.

currently  my debug code is 

```python

ds = myDataset(subset='train')

from models.ctc_with_priors import CTCLossWithLabelPriors, ctc_loss

# loss_fn = CTCLossWithLabelPriors(
#     prior_scaling_factor=0.2,  # 0.0 means no label priors  
#     blank=0,
# )
# in the CTCLossWithLabelPriors.forward()
# loss = ctc_loss(
#        log_probs_with_priors, 
#        targets.to(torch.int64), 
#        input_lengths.to(torch.int64), 
#        target_lengths.to(torch.int64), 
#        blank=self.blank, 
# ).sum()
# return loss


loss_fn = ctc_loss

model = torch.nn.Linear(
    ds.ch_tokenizer.vocab_size, ds.ch_tokenizer.vocab_size
)
optim = torch.optim.Adam(model.parameters(), lr=1e-4)

feats = torch.randn(20, 10, ds.ch_tokenizer.vocab_size)
targets = torch.randint(0, ds.ch_tokenizer.vocab_size, (10, 10))
input_length = torch.randint(1, 20, (10,))
target_lengths = torch.randint(1, 10, (10,))

with torch.autograd.set_detect_anomaly(True):

    log_probs = model(feats).log_softmax(dim=-1)
    loss = loss_fn(log_probs, targets, input_length, target_lengths).sum()
    optim.zero_grad()
    loss.backward()
    optim.step()

```

then I got errors like
```python
/conda/envs/mandob/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in StackBackward0. Traceback of forward call that caused the error:
  File "/home/code/projects-cm/debug.py", line 49, in <module>
    loss = loss_fn(log_probs, targets, input_length, target_lengths).sum()
  File "/home/code/projects-cm/models/ctc_with_priors.py", line 55, in ctc_loss
    log_alpha[t, :, 2:] = log_probs_[t] + logadd(log_alpha[t - 1, :, 2:], log_alpha[t - 1, :, 1:-1], torch.where(diff_labels, log_alpha[t - 1, :, :-2], zero))
  File "/home/code/projects-cm/models/ctc_with_priors.py", line 66, in logadd
    return torch.logsumexp(torch.stack([x0, x1, x2]), dim = 0)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484772832/work/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/home/code/Caffine-MandOb/debug.py", line 51, in <module>
    loss.backward()
  File "/conda/envs/mandob/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/conda/envs/mandob/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10, 22]], which is output 0 of AsStridedBackward0, is at version 22; expected version 21 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

my environments is 
```bash
Linux 3.10.0-1062.9.1.el7.x86_64
conda 4.10.3
Python 3.10.16 [GCC 11.2.0] on linux
pytorch 1.12.1          py3.10_cuda10.2_cudnn7.6.5_0 
pytorch-lightning         2.0.3               
```

I will try adding `.clone()` but wondering some memory friendly solutions maybe

**Comment by vadimkantorov** [comment]
Maybe one way could be unbinding the log_alpha, and filling inplace the individual tensors?

Or somewhere adding some hacks to avoid update of tensor version...

If you isolate a small example, feel free to ask at pytorch forum or issues

Also feel free to browse the commit history to some early commit, where this seemed to work

**Comment by vadimkantorov** [comment]
Also, if you can post a complete single-file toy data repro, I might be able to debug it

**Comment by YangLeiSX** [comment]
thanks for you reply.
I re-check my code and test it on different devices.

the code got previous RuntimeError on CentOS with PyTorch 1.12(CUDA 10.2).
but it works well on MacOS with PyTorch 2.2(no GPU).

Finally I convert the `logadd` implementation to `LogsumexpFunction.apply()`
Now it works well on both environments.

I'm not sure why, I post my toy repro as bellow.
```python
  vocab_size = 64

  model = torch.nn.Linear(
      vocab_size, vocab_size
  )

  optim = torch.optim.Adam(model.parameters(), lr=1e-4)
  feats = torch.randn(20, 10, vocab_size)
  targets = torch.randint(0, vocab_size, (10, 10))
  input_length = torch.randint(1, 20, (10,))
  target_lengths = torch.randint(1, 10, (10,))

  with torch.autograd.set_detect_anomaly(True):
      log_probs = model(feats).log_softmax(dim=-1)
      loss = ctc_loss(log_probs, targets, input_length, target_lengths).sum()
      optim.zero_grad()
      loss.backward()
      optim.step()
```

on the Centos with PyTorch 1.12 and cuda10.2, the error is 
```bash
/conda/envs/mandob/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in StackBackward0. Traceback of forward call that caused the error:
  File "/code/raw_ctc.py", line 81, in <module>
    loss = ctc_loss(log_probs, targets, input_length, target_lengths).sum()
  File "/code/raw_ctc.py", line 26, in ctc_loss
    log_alpha[t, :, 2:] = log_probs_[t] + logadd(log_alpha[t - 1, :, 2:], log_alpha[t - 1, :, 1:-1], torch.where(diff_labels, log_alpha[t - 1, :, :-2], zero))
  File "/code/raw_ctc.py", line 34, in logadd
    return torch.logsumexp(torch.stack([x0, x1, x2]), dim = 0)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484772832/work/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/code/raw_ctc.py", line 83, in <module>
    loss.backward()
  File "/conda/envs/mandob/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/conda/envs/mandob/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10, 22]], which is output 0 of AsStridedBackward0, is at version 22; expected version 21 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```
